### ISSUE TITLE
network-queue-process.patch

### ISSUE THREAD

**Issue by andreasdc** [starlis/empirecraft#11]
Is network-queue-process.patch safe to use?

**Comment by aikar** [comment]
That was a joke patch but it functionally worked when it was created, but I have no real experience if it causes any real issues and would need to be ported to the latest version of MC too.

It is not recommended in production unless you can do some serious testing. I can't verify it even solves any problems.

**Comment by andreasdc** [comment]
> That was a joke patch but it functionally worked when it was created, but I have no real experience if it causes any real issues and would need to be ported to the latest version of MC too.
> 
> It is not recommended in production unless you can do some serious testing. I can't verify it even solves any problems.

I was scared that it would make desync, but I thought without this patch packets are dispatched instanly, and I see they are dependent of the tick time?
