### ISSUE TITLE
EntityEffectAddedEvent uses wrong PotionEffect

### ISSUE THREAD

**Issue by SoSeDiK** [starlis/empirecraft#5]
PotionEffect in `0027-Add-EntityEffectAddedEvent.patch` does not include predefined `mobeffect.isAmbient(), mobeffect.isShowParticles(), mobeffect.isShowIcon()` values (line 21).
Also, new PotionEffect does not include `effect.hasIcon()`, so `effect.hasParticles()` always controls icon instead (line 26).

**Comment by chickeneer** [comment]
https://github.com/starlis/empirecraft/commit/c32b39902f303c4d1e0437dfbb38856644a9ac66
Fixed in this commit. Failed to tag correctly. Failing to look what issue number this was. Silly me.
